### ISSUE TITLE
关于Aria2_Web.exe的下载网站 

### ISSUE THREAD

**Issue by 00randomize00** [sayokey/link-helper#41]
- 描述你的错误: 请问作者能不能把Aria2_Web.exe 放在其他的网盘？因为我是海外用户无法下载 😢

**Comment by sayokey** [comment]
你可以在Google 中搜索  Aria2 Ng , 他们都适用

**Comment by 00randomize00** [comment]
Aria2 Ng我下载了，可是我无法推送去aria2下载。Aria2 不用下载跟IDMSERVER.exe 一样的软件来推送吗？如果有的话，我是指那个推送去aria2软件的下载网站

**Comment by sayokey** [comment]
不需要 Aria2本身就自带了 IDMSERVER 只是中转数据的

**Comment by 00randomize00** [comment]
描述你的错误: 我尝试了很多次还是无法发送去aria2下载
在哪个页面发生的:http://www.xunniupan.co/file-2636968.html
版本号: 2.3.3
油猴版本: 4.18.1
浏览器: Google Chrome
开发者控制台截图:
![image](https://user-images.githubusercontent.com/116192690/207053692-488c820d-55a3-4fd9-ad60-8be864308215.png)
![image](https://user-images.githubusercontent.com/116192690/207053843-1a495206-e6ca-45f4-bea7-d2dae7b1d299.png)
![image](https://user-images.githubusercontent.com/116192690/207053890-91774d33-58d7-43dd-9bac-10c0e5e8cfc8.png)

**Comment by sayokey** [comment]
点击浏览器查看是否可以正常跳转下载

**Comment by 00randomize00** [comment]
![1](https://user-images.githubusercontent.com/116192690/207325514-ef06ed2a-37f2-4afc-a0a5-da04ba8b340c.jpg)
![2](https://user-images.githubusercontent.com/116192690/207325543-19fb4ac9-f0c0-40fc-90ed-fe2414b7f505.jpg)
浏览器下载和idm下载都没有问题。只有aria2不行

**Comment by sayokey** [comment]
可能是Aria设置问题 你可以查看Aria的推送地址是否与脚本默认的相同 并且查看是否设置了秘钥

**Comment by 00randomize00** [comment]
![1](https://user-images.githubusercontent.com/116192690/207606795-068fddac-9811-4ffe-978d-9c4a34ca7608.png)
![2](https://user-images.githubusercontent.com/116192690/207606891-7803911a-85b6-475f-a7b2-01b0dc6032a8.png)
ok 可以了，原来是要加秘钥。感谢作者
