### ISSUE TITLE
idm下载星耀盘文件时显示“连接失败，正在重新连接”，以切换本地代理，不行。

### ISSUE THREAD

**Issue by StarLi-zh** [sayokey/link-helper#43]
- 描述你的错误:(最短的话将它描述出来)
- 在哪个页面发生的:(这里提供错误页面的链接地址)
- 版本号:(你所使用的脚本版本号)
- 油猴版本:(你所使用的油猴版本)
- 浏览器:(你所使用的浏览器)
- 开发者控制台截图:(你需要提供一张或多张控制台信息截图,请在出现错误前打开控制台,以方便记录所有日志,不要吝啬一张图片,你可以将它更完整)

**Comment by sayokey** [comment]
这是星耀云的问题
