### ISSUE TITLE
1988网盘失效

### ISSUE THREAD

**Issue by david9965** [sayokey/link-helper#45]
- 描述你的错误:1988网盘失效，付费资源无法下载，免费的也是404
- 在哪个页面发生的:http://www.1988wp.com/file-9302.html
- 版本号:最新
- 油猴版本:最新
- 浏览器:chrome
- 开发者控制台截图:(你需要提供一张或多张控制台信息截图,请在出现错误前打开控制台,以方便记录所有日志,不要吝啬一张图片,你可以将它更完整)

**Comment by sayokey** [comment]
这是他的问题
